# Site settings
title: Robots with Hearts
email: ihm@robotswithhearts.org
description: > # this means to ignore newlines until "baseurl:"
  A blog about society & technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.robotswithhearts.org" # the base hostname & protocol for your site
github_username: ihmccreery

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
